/// Raw UDP socket via Linux syscalls — no libc
/// Generated by LLM, will be reviewed and properly tested later. Just for prototyping.
/// I don't know asm properly and I don't know the syscalls

const AF_INET: usize    = 2;
const SOCK_DGRAM: usize = 2;
const SOL_SOCKET: usize = 1;
const SO_RCVTIMEO: usize = 20;

const SYS_SOCKET:     usize = 41;
const SYS_SENDTO:     usize = 44;
const SYS_RECVFROM:   usize = 45;
const SYS_CLOSE:      usize = 3;
const SYS_SETSOCKOPT: usize = 54;

#[repr(C)]
struct SockAddrIn {
    family: u16,
    port:   u16,
    addr:   [u8; 4],
    zero:   [u8; 8],
}

#[repr(C)]
struct Timeval {
    tv_sec:  u64,
    tv_usec: u64,
}

/// Send a DNS query over UDP and receive the response
/// Returns number of bytes in response, or None on failure
pub fn udp_query(
    server: [u8; 4],
    port:   u16,
    query:  &[u8],
    resp:   &mut [u8],
    timeout_sec: u64,
) -> Option<usize> {
    unsafe {
        // socket()
        let fd = syscall3(SYS_SOCKET, AF_INET, SOCK_DGRAM, 0);
        if fd < 0 { return None; }
        let fd = fd as usize;

        // Set receive timeout
        let tv = Timeval { tv_sec: timeout_sec, tv_usec: 0 };
        syscall5(
            SYS_SETSOCKOPT,
            fd,
            SOL_SOCKET,
            SO_RCVTIMEO,
            &tv as *const _ as usize,
            core::mem::size_of::<Timeval>(),
        );

        let addr = SockAddrIn {
            family: AF_INET as u16,
            port:   port.to_be(),
            addr:   server,
            zero:   [0u8; 8],
        };

        // sendto()
        let sent = syscall6(
            SYS_SENDTO,
            fd,
            query.as_ptr() as usize,
            query.len(),
            0,
            &addr as *const _ as usize,
            core::mem::size_of::<SockAddrIn>(),
        );

        if sent < 0 {
            syscall1(SYS_CLOSE, fd);
            return None;
        }

        // recvfrom()
        let received = syscall6(
            SYS_RECVFROM,
            fd,
            resp.as_mut_ptr() as usize,
            resp.len(),
            0, 0, 0,
        );

        syscall1(SYS_CLOSE, fd);

        if received > 0 {
            Some(received as usize)
        } else {
            None
        }
    }
}

// ── Raw syscall wrappers (x86_64 Linux) ──────────────────

unsafe fn syscall1(n: usize, a: usize) -> isize {
    let ret: isize;
    core::arch::asm!(
        "syscall",
        in("rax") n, in("rdi") a,
        lateout("rax") ret,
        out("rcx") _, out("r11") _,
    );
    ret
}

unsafe fn syscall3(n: usize, a: usize, b: usize, c: usize) -> isize {
    let ret: isize;
    core::arch::asm!(
        "syscall",
        in("rax") n, in("rdi") a, in("rsi") b, in("rdx") c,
        lateout("rax") ret,
        out("rcx") _, out("r11") _,
    );
    ret
}

unsafe fn syscall5(n: usize, a: usize, b: usize, c: usize, d: usize, e: usize) -> isize {
    let ret: isize;
    core::arch::asm!(
        "syscall",
        in("rax") n, in("rdi") a, in("rsi") b, in("rdx") c,
        in("r10") d, in("r8") e,
        lateout("rax") ret,
        out("rcx") _, out("r11") _,
    );
    ret
}

unsafe fn syscall6(
    n: usize, a: usize, b: usize, c: usize,
    d: usize, e: usize, f: usize,
) -> isize {
    let ret: isize;
    core::arch::asm!(
        "syscall",
        in("rax") n, in("rdi") a, in("rsi") b, in("rdx") c,
        in("r10") d, in("r8") e, in("r9") f,
        lateout("rax") ret,
        out("rcx") _, out("r11") _,
    );
    ret
}